### ISSUE TITLE
Use of JWT token or other kind of token and HTTPS possible ?

### ISSUE THREAD

**Issue by nyrull** [aldycool/NETCoreSync#2]
Hi, it is me again ! haha

I am looking at different approach to secure my web api and wanted to know if it could be possible to implement JWT Token or another kind of token in NetCoreSync.

As https it should be possible right ?

Thank you again.

**Comment by aldycool** [comment]
Hi, hello again :D

About the JWT Tokens (or any other token mechanism to secure the communication), on how to create the JWT token is of course beyond the scope of this framework. For example, this stackoverflow link explains nicely on how to create and consume the JWT token in detail (assuming you haven't know about this): https://stackoverflow.com/questions/40281050/jwt-authentication-for-asp-net-web-api. Looking at the stackoverflow explanation, basically the client should already have a `token` (which is some random string generated on the server that uniquely identified the caller) that needs to be carried along with the HTTP request when calling the `SyncClient.SynchronizeAsync`. On the server side, this `token` is examined to determine whether the caller is allowed to access the api, which also already explained in the discussion on how to do this. The one this is missing, right now the `SyncClient.AuthorizeAsync` does not support adding such token in its call. JWT Token (or any major token mechanism, such as basic http authentication) is usually uses the HTTP header to embed the token information. Let me see what I can do to support this, maybe I will add an overload `SyncClient.AuthorizeAsync` method that have a `Dictionary<string, string>` argument, so you can create this dictionary, add the JWT token in here, and pass the dictionary to the method call to embed the token information. And later on the server side (on the `SyncController.Index` endpoint) you can inspect this token information yourself before calling the syncServer.Process`. Is this approach is feasible for you? please let me know your thoughts on this.

As for the https, actually this can be done on the server level only. This can be done by always enforcing the https protocol during the ASP.NET `Startup.Configure`, as explained in this article: https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio.

**Comment by nyrull** [comment]
Hi, 

What i meant is, if it could be possible, to pass a token in its call, not implement the all thing. Sorry for the misunderstand, my knowledge of english does not help me to fully express what i have in mind :)

Could you make an overload for `SyncClient` constructor like 
```C#
       //Add new property
        private readonly string token;

         public SyncClient(string synchronizationId, SyncEngine syncEngine, string serverUrl, string token = "")
        {
            this.synchronizationId = synchronizationId ?? throw new NullReferenceException(nameof(synchronizationId));
            this.syncEngine = syncEngine ?? throw new NullReferenceException(nameof(syncEngine));
            this.serverUrl = serverUrl ?? throw new NullReferenceException(nameof(serverUrl));

            //Add this
            this.token = string.IsNullOrEmpty(token) ? string.Empty : token;
        }
```

and in the async task ` private async Task<(string errorMessage, JObject payload)> ExecuteOnServer(byte[] compressed, SyncResult syncResult)` after the creation of the HttpClient you could check if there is a token and update the default request headers like that

```C#
        private async Task<(string errorMessage, JObject payload)> ExecuteOnServer(byte[] compressed, SyncResult syncResult)
        {
            JObject payload = null;

            using (var httpClient = new HttpClient())
            {
                //Check if we have a token
                if (!string.IsNullOrEmpty(this.token))
                {
                    //Set header with token
                    httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", this.token);
                }

                using (var multipartFormDataContent = new MultipartFormDataContent())
                {
                    ByteArrayContent byteArrayContent = new ByteArrayContent(compressed);
                    multipartFormDataContent.Add(byteArrayContent, "files", "compressed.data");
                    var response = await httpClient.PostAsync(serverUrl, multipartFormDataContent);

                    if (response.IsSuccessStatusCode)
```

Let me know what you think of it.

Thanks !

**Comment by aldycool** [comment]
Hi,

It's not a problem, I now fully understand what you mean and I'm glad we actually thinking the same thing.

I've implemented what you've requested in the latest version (v1.2.1) and its nuget package is already published. But it differs a little in how to pass the token into the `SyncClient`. Now there's a new overload constructor for the `SyncClient`, but it accept a `Dictionary<string, string>` rather than a simple `string` for the token. The idea is, I think it would be better to prepare for the future if there are other needs to embed some custom HTTP header (other than for `Authorization` type), so the constructor would not change again for HTTP header purposes.

As for your authorization needs, you can create a `Dictionary<string, string>` variable, add it with key = "Authorization" and value = "Bearer [yourtokenhere"]. This approach will have the same effect as you've demonstrated in your previous code.

Thanks for the input and please let me know if there are more suggestions.

**Comment by nyrull** [comment]
Great, it will work well i think.

Thank you for taking your time to add this.
